/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedCargosRouteImport } from './routes/_authenticated/cargos'
import { Route as AuthenticatedArquivoRouteImport } from './routes/_authenticated/arquivo'
import { Route as AuthenticatedAbertosRouteImport } from './routes/_authenticated/abertos'
import { Route as AuthenticatedPerfilIdRouteImport } from './routes/_authenticated/perfil.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCargosRoute = AuthenticatedCargosRouteImport.update({
  id: '/cargos',
  path: '/cargos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedArquivoRoute = AuthenticatedArquivoRouteImport.update({
  id: '/arquivo',
  path: '/arquivo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAbertosRoute = AuthenticatedAbertosRouteImport.update({
  id: '/abertos',
  path: '/abertos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilIdRoute = AuthenticatedPerfilIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedPerfilRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/abertos': typeof AuthenticatedAbertosRoute
  '/arquivo': typeof AuthenticatedArquivoRoute
  '/cargos': typeof AuthenticatedCargosRoute
  '/perfil': typeof AuthenticatedPerfilRouteWithChildren
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/perfil/$id': typeof AuthenticatedPerfilIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/abertos': typeof AuthenticatedAbertosRoute
  '/arquivo': typeof AuthenticatedArquivoRoute
  '/cargos': typeof AuthenticatedCargosRoute
  '/perfil': typeof AuthenticatedPerfilRouteWithChildren
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/': typeof AuthenticatedIndexRoute
  '/perfil/$id': typeof AuthenticatedPerfilIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/abertos': typeof AuthenticatedAbertosRoute
  '/_authenticated/arquivo': typeof AuthenticatedArquivoRoute
  '/_authenticated/cargos': typeof AuthenticatedCargosRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRouteWithChildren
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/perfil/$id': typeof AuthenticatedPerfilIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/abertos'
    | '/arquivo'
    | '/cargos'
    | '/perfil'
    | '/usuarios'
    | '/perfil/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/abertos'
    | '/arquivo'
    | '/cargos'
    | '/perfil'
    | '/usuarios'
    | '/'
    | '/perfil/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/abertos'
    | '/_authenticated/arquivo'
    | '/_authenticated/cargos'
    | '/_authenticated/perfil'
    | '/_authenticated/usuarios'
    | '/_authenticated/'
    | '/_authenticated/perfil/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cargos': {
      id: '/_authenticated/cargos'
      path: '/cargos'
      fullPath: '/cargos'
      preLoaderRoute: typeof AuthenticatedCargosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/arquivo': {
      id: '/_authenticated/arquivo'
      path: '/arquivo'
      fullPath: '/arquivo'
      preLoaderRoute: typeof AuthenticatedArquivoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/abertos': {
      id: '/_authenticated/abertos'
      path: '/abertos'
      fullPath: '/abertos'
      preLoaderRoute: typeof AuthenticatedAbertosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil/$id': {
      id: '/_authenticated/perfil/$id'
      path: '/$id'
      fullPath: '/perfil/$id'
      preLoaderRoute: typeof AuthenticatedPerfilIdRouteImport
      parentRoute: typeof AuthenticatedPerfilRoute
    }
  }
}

interface AuthenticatedPerfilRouteChildren {
  AuthenticatedPerfilIdRoute: typeof AuthenticatedPerfilIdRoute
}

const AuthenticatedPerfilRouteChildren: AuthenticatedPerfilRouteChildren = {
  AuthenticatedPerfilIdRoute: AuthenticatedPerfilIdRoute,
}

const AuthenticatedPerfilRouteWithChildren =
  AuthenticatedPerfilRoute._addFileChildren(AuthenticatedPerfilRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAbertosRoute: typeof AuthenticatedAbertosRoute
  AuthenticatedArquivoRoute: typeof AuthenticatedArquivoRoute
  AuthenticatedCargosRoute: typeof AuthenticatedCargosRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRouteWithChildren
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAbertosRoute: AuthenticatedAbertosRoute,
  AuthenticatedArquivoRoute: AuthenticatedArquivoRoute,
  AuthenticatedCargosRoute: AuthenticatedCargosRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRouteWithChildren,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
